// Code generated by go generate; DO NOT EDIT.

package params

import (
	"math/big"

	"github.com/XinFinOrg/XDPoSChain/common"
)

var generatedChainConfigCommonBackfillBigIntFields = []chainConfigBigIntField{
	{
		name:    "ChainID",
		jsonKey: "chainId",
		get:     func(c *ChainConfig) *big.Int { return c.ChainID },
		bind:    func(c *ChainConfig) **big.Int { return &c.ChainID },
	},
	{
		name:    "HomesteadBlock",
		jsonKey: "homesteadBlock",
		get:     func(c *ChainConfig) *big.Int { return c.HomesteadBlock },
		bind:    func(c *ChainConfig) **big.Int { return &c.HomesteadBlock },
	},
	{
		name:    "DAOForkBlock",
		jsonKey: "daoForkBlock",
		get:     func(c *ChainConfig) *big.Int { return c.DAOForkBlock },
		bind:    func(c *ChainConfig) **big.Int { return &c.DAOForkBlock },
	},
	{
		name:    "EIP150Block",
		jsonKey: "eip150Block",
		get:     func(c *ChainConfig) *big.Int { return c.EIP150Block },
		bind:    func(c *ChainConfig) **big.Int { return &c.EIP150Block },
	},
	{
		name:    "EIP155Block",
		jsonKey: "eip155Block",
		get:     func(c *ChainConfig) *big.Int { return c.EIP155Block },
		bind:    func(c *ChainConfig) **big.Int { return &c.EIP155Block },
	},
	{
		name:    "EIP158Block",
		jsonKey: "eip158Block",
		get:     func(c *ChainConfig) *big.Int { return c.EIP158Block },
		bind:    func(c *ChainConfig) **big.Int { return &c.EIP158Block },
	},
	{
		name:    "ByzantiumBlock",
		jsonKey: "byzantiumBlock",
		get:     func(c *ChainConfig) *big.Int { return c.ByzantiumBlock },
		bind:    func(c *ChainConfig) **big.Int { return &c.ByzantiumBlock },
	},
	{
		name:    "ConstantinopleBlock",
		jsonKey: "constantinopleBlock",
		get:     func(c *ChainConfig) *big.Int { return c.ConstantinopleBlock },
		bind:    func(c *ChainConfig) **big.Int { return &c.ConstantinopleBlock },
	},
	{
		name:    "PetersburgBlock",
		jsonKey: "petersburgBlock",
		get:     func(c *ChainConfig) *big.Int { return c.PetersburgBlock },
		bind:    func(c *ChainConfig) **big.Int { return &c.PetersburgBlock },
	},
	{
		name:    "IstanbulBlock",
		jsonKey: "istanbulBlock",
		get:     func(c *ChainConfig) *big.Int { return c.IstanbulBlock },
		bind:    func(c *ChainConfig) **big.Int { return &c.IstanbulBlock },
	},
}

var generatedChainConfigBuiltInBackfillForkBlockFields = []chainConfigBigIntField{
	{
		name:    "BerlinBlock",
		jsonKey: "berlinBlock",
		get:     func(c *ChainConfig) *big.Int { return c.BerlinBlock },
		bind:    func(c *ChainConfig) **big.Int { return &c.BerlinBlock },
	},
	{
		name:    "LondonBlock",
		jsonKey: "londonBlock",
		get:     func(c *ChainConfig) *big.Int { return c.LondonBlock },
		bind:    func(c *ChainConfig) **big.Int { return &c.LondonBlock },
	},
	{
		name:    "MergeBlock",
		jsonKey: "mergeBlock",
		get:     func(c *ChainConfig) *big.Int { return c.MergeBlock },
		bind:    func(c *ChainConfig) **big.Int { return &c.MergeBlock },
	},
	{
		name:    "ShanghaiBlock",
		jsonKey: "shanghaiBlock",
		get:     func(c *ChainConfig) *big.Int { return c.ShanghaiBlock },
		bind:    func(c *ChainConfig) **big.Int { return &c.ShanghaiBlock },
	},
	{
		name:    "EIP1559Block",
		jsonKey: "eip1559Block",
		get:     func(c *ChainConfig) *big.Int { return c.EIP1559Block },
		bind:    func(c *ChainConfig) **big.Int { return &c.EIP1559Block },
	},
	{
		name:    "CancunBlock",
		jsonKey: "cancunBlock",
		get:     func(c *ChainConfig) *big.Int { return c.CancunBlock },
		bind:    func(c *ChainConfig) **big.Int { return &c.CancunBlock },
	},
	{
		name:    "PragueBlock",
		jsonKey: "pragueBlock",
		get:     func(c *ChainConfig) *big.Int { return c.PragueBlock },
		bind:    func(c *ChainConfig) **big.Int { return &c.PragueBlock },
	},
	{
		name:    "OsakaBlock",
		jsonKey: "osakaBlock",
		get:     func(c *ChainConfig) *big.Int { return c.OsakaBlock },
		bind:    func(c *ChainConfig) **big.Int { return &c.OsakaBlock },
	},
	{
		name:           "TIP2019Block",
		jsonKey:        "tip2019Block",
		customMigrated: true,
		xdcSpecific:    true,
		get:            func(c *ChainConfig) *big.Int { return c.TIP2019Block },
		bind:           func(c *ChainConfig) **big.Int { return &c.TIP2019Block },
	},
	{
		name:           "TIPSigningBlock",
		jsonKey:        "tipSigningBlock",
		customMigrated: true,
		xdcSpecific:    true,
		get:            func(c *ChainConfig) *big.Int { return c.TIPSigningBlock },
		bind:           func(c *ChainConfig) **big.Int { return &c.TIPSigningBlock },
	},
	{
		name:           "TIPRandomizeBlock",
		jsonKey:        "tipRandomizeBlock",
		customMigrated: true,
		xdcSpecific:    true,
		get:            func(c *ChainConfig) *big.Int { return c.TIPRandomizeBlock },
		bind:           func(c *ChainConfig) **big.Int { return &c.TIPRandomizeBlock },
	},
	{
		name:           "TIPIncreaseMasternodesBlock",
		jsonKey:        "tipIncreaseMasternodesBlock",
		customMigrated: true,
		xdcSpecific:    true,
		get:            func(c *ChainConfig) *big.Int { return c.TIPIncreaseMasternodesBlock },
		bind:           func(c *ChainConfig) **big.Int { return &c.TIPIncreaseMasternodesBlock },
	},
	{
		name:           "DenylistBlock",
		jsonKey:        "denylistBlock",
		customMigrated: true,
		xdcSpecific:    true,
		get:            func(c *ChainConfig) *big.Int { return c.DenylistBlock },
		bind:           func(c *ChainConfig) **big.Int { return &c.DenylistBlock },
	},
	{
		name:           "TIPNoHalvingMNRewardBlock",
		jsonKey:        "tipNoHalvingMNRewardBlock",
		customMigrated: true,
		xdcSpecific:    true,
		get:            func(c *ChainConfig) *big.Int { return c.TIPNoHalvingMNRewardBlock },
		bind:           func(c *ChainConfig) **big.Int { return &c.TIPNoHalvingMNRewardBlock },
	},
	{
		name:           "TIPXDCXBlock",
		jsonKey:        "tipXDCXBlock",
		customMigrated: true,
		xdcSpecific:    true,
		get:            func(c *ChainConfig) *big.Int { return c.TIPXDCXBlock },
		bind:           func(c *ChainConfig) **big.Int { return &c.TIPXDCXBlock },
	},
	{
		name:           "TIPXDCXLendingBlock",
		jsonKey:        "tipXDCXLendingBlock",
		customMigrated: true,
		xdcSpecific:    true,
		get:            func(c *ChainConfig) *big.Int { return c.TIPXDCXLendingBlock },
		bind:           func(c *ChainConfig) **big.Int { return &c.TIPXDCXLendingBlock },
	},
	{
		name:           "TIPXDCXCancellationFeeBlock",
		jsonKey:        "tipXDCXCancellationFeeBlock",
		customMigrated: true,
		xdcSpecific:    true,
		get:            func(c *ChainConfig) *big.Int { return c.TIPXDCXCancellationFeeBlock },
		bind:           func(c *ChainConfig) **big.Int { return &c.TIPXDCXCancellationFeeBlock },
	},
	{
		name:           "TIPTRC21FeeBlock",
		jsonKey:        "tipTRC21FeeBlock",
		customMigrated: true,
		xdcSpecific:    true,
		get:            func(c *ChainConfig) *big.Int { return c.TIPTRC21FeeBlock },
		bind:           func(c *ChainConfig) **big.Int { return &c.TIPTRC21FeeBlock },
	},
	{
		name:           "Gas50xBlock",
		jsonKey:        "gas50xBlock",
		customMigrated: true,
		xdcSpecific:    true,
		get:            func(c *ChainConfig) *big.Int { return c.Gas50xBlock },
		bind:           func(c *ChainConfig) **big.Int { return &c.Gas50xBlock },
	},
	{
		name:        "TIPXDCXMinerDisableBlock",
		jsonKey:     "tipXDCXMinerDisableBlock",
		xdcSpecific: true,
		get:         func(c *ChainConfig) *big.Int { return c.TIPXDCXMinerDisableBlock },
		bind:        func(c *ChainConfig) **big.Int { return &c.TIPXDCXMinerDisableBlock },
	},
	{
		name:        "TIPXDCXReceiverDisableBlock",
		jsonKey:     "tipXDCXReceiverDisableBlock",
		xdcSpecific: true,
		get:         func(c *ChainConfig) *big.Int { return c.TIPXDCXReceiverDisableBlock },
		bind:        func(c *ChainConfig) **big.Int { return &c.TIPXDCXReceiverDisableBlock },
	},
	{
		name:        "DynamicGasLimitBlock",
		jsonKey:     "dynamicGasLimitBlock",
		xdcSpecific: true,
		get:         func(c *ChainConfig) *big.Int { return c.DynamicGasLimitBlock },
		bind:        func(c *ChainConfig) **big.Int { return &c.DynamicGasLimitBlock },
	},
	{
		name:        "TIPUpgradeRewardBlock",
		jsonKey:     "tipUpgradeRewardBlock",
		xdcSpecific: true,
		get:         func(c *ChainConfig) *big.Int { return c.TIPUpgradeRewardBlock },
		bind:        func(c *ChainConfig) **big.Int { return &c.TIPUpgradeRewardBlock },
	},
	{
		name:        "TIPUpgradePenaltyBlock",
		jsonKey:     "tipUpgradePenaltyBlock",
		xdcSpecific: true,
		get:         func(c *ChainConfig) *big.Int { return c.TIPUpgradePenaltyBlock },
		bind:        func(c *ChainConfig) **big.Int { return &c.TIPUpgradePenaltyBlock },
	},
	{
		name:        "TIPEpochHalvingBlock",
		jsonKey:     "tipEpochHalvingBlock",
		xdcSpecific: true,
		get:         func(c *ChainConfig) *big.Int { return c.TIPEpochHalvingBlock },
		bind:        func(c *ChainConfig) **big.Int { return &c.TIPEpochHalvingBlock },
	},
}

var generatedChainConfigForkOrderFieldDefs = []struct {
	name     string
	optional func(*ChainConfig) bool
}{
	{
		name:     "HomesteadBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "TIP2019Block",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "DAOForkBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "EIP150Block",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "EIP155Block",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "EIP158Block",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "ByzantiumBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "ConstantinopleBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "PetersburgBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "IstanbulBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "TIPSigningBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "TIPRandomizeBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "TIPIncreaseMasternodesBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "DenylistBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "TIPNoHalvingMNRewardBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "TIPXDCXBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "TIPXDCXLendingBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "TIPXDCXCancellationFeeBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "TIPTRC21FeeBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "BerlinBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "LondonBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "MergeBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "ShanghaiBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "TIPXDCXMinerDisableBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "TIPXDCXReceiverDisableBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "EIP1559Block",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "CancunBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "PragueBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "OsakaBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "DynamicGasLimitBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "TIPUpgradeRewardBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "TIPUpgradePenaltyBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
	{
		name:     "TIPEpochHalvingBlock",
		optional: alwaysOptionalChainConfigForkOrderField,
	},
}

var generatedChainConfigXDCSystemContractFields = []chainConfigAddressField{
	{
		name:    "TRC21IssuerSMC",
		jsonKey: "trc21IssuerSMC",
		get:     func(c *ChainConfig) common.Address { return c.TRC21IssuerSMC },
		bind:    func(c *ChainConfig) *common.Address { return &c.TRC21IssuerSMC },
		compat:  func(c *ChainConfig) *big.Int { return c.TIPTRC21FeeBlock },
	},
	{
		name:    "XDCXListingSMC",
		jsonKey: "xdcxListingSMC",
		get:     func(c *ChainConfig) common.Address { return c.XDCXListingSMC },
		bind:    func(c *ChainConfig) *common.Address { return &c.XDCXListingSMC },
		compat:  func(c *ChainConfig) *big.Int { return c.TIPXDCXBlock },
	},
	{
		name:    "RelayerRegistrationSMC",
		jsonKey: "relayerRegistrationSMC",
		get:     func(c *ChainConfig) common.Address { return c.RelayerRegistrationSMC },
		bind:    func(c *ChainConfig) *common.Address { return &c.RelayerRegistrationSMC },
		compat:  func(c *ChainConfig) *big.Int { return c.TIPXDCXBlock },
	},
	{
		name:    "LendingRegistrationSMC",
		jsonKey: "lendingRegistrationSMC",
		get:     func(c *ChainConfig) common.Address { return c.LendingRegistrationSMC },
		bind:    func(c *ChainConfig) *common.Address { return &c.LendingRegistrationSMC },
		compat:  func(c *ChainConfig) *big.Int { return c.TIPXDCXLendingBlock },
	},
}
