// Copyright 2026 The go-ethereum Authors
// This file is part of the go-ethereum library.
//
// The go-ethereum library is free software: you can redistribute it and/or modify
// it under the terms of the GNU Lesser General Public License as published by
// the Free Software Foundation, either version 3 of the License, or
// (at your option) any later version.
//
// The go-ethereum library is distributed in the hope that it will be useful,
// but WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE. See the
// GNU Lesser General Public License for more details.
//
// You should have received a copy of the GNU Lesser General Public License
// along with the go-ethereum library. If not, see <http://www.gnu.org/licenses/>.

package bind_test

import (
	"testing"

	"github.com/XinFinOrg/XDPoSChain/accounts/abi/bind/v2"
	"github.com/XinFinOrg/XDPoSChain/accounts/abi/bind/v2/internal/contracts/events"
	"github.com/XinFinOrg/XDPoSChain/common"
	"github.com/XinFinOrg/XDPoSChain/core/types"
)

// This file is the only carrier of the cases pinning the event signature
// sentinel errors. Upstream keeps them in accounts/abi/bind/v2/lib_test.go, a
// file this repository does not carry: TestEventUnpackEmptyTopics, and
// TestWatchEventsIgnoreMismatch, which upstream master already has but which
// only lands here with the ignore-mismatch change. A later port of that file
// must not bring the same-named functions along, as two tests with one name in
// package bind_test do not compile.

// TestEventUnpackEmptyTopics checks that the unpacker generated by abigen --v2
// reports a log that carries no topics, and a log whose first topic is not the
// event ID, with the exported sentinel errors rather than with an error created
// on the spot. The sentinels are exported so that generated code outside the
// package can return them, which is what lets a caller tell a log it did not ask
// for apart from a genuine decoding failure; the assertions below compare the
// errors by identity, which is stricter than an errors.Is match.
func TestEventUnpackEmptyTopics(t *testing.T) {
	c := events.NewC()

	for _, log := range []*types.Log{
		{Topics: []common.Hash{}},
		{Topics: nil},
	} {
		_, err := c.UnpackBasic1Event(log)
		if err == nil {
			t.Fatal("expected error when unpacking event with empty topics, got nil")
		}
		if err != bind.ErrNoEventSignature {
			t.Fatalf("expected 'no event signature' error, got: %v", err)
		}

		_, err = c.UnpackBasic2Event(log)
		if err == nil {
			t.Fatal("expected error when unpacking event with empty topics, got nil")
		}
		if err != bind.ErrNoEventSignature {
			t.Fatalf("expected 'no event signature' error, got: %v", err)
		}
	}
	// Non-empty topics that do not belong to the expected event.
	_, err := c.UnpackBasic1Event(&types.Log{Topics: []common.Hash{common.HexToHash("0x01")}})
	if err == nil {
		t.Fatal("expected error when unpacking event with foreign topics, got nil")
	}
	if err != bind.ErrEventSignatureMismatch {
		t.Fatalf("expected 'event signature mismatch' error, got: %v", err)
	}
}
